### ISSUE TITLE
Socket is not connected (Errno::ENOTCONN)

### ISSUE THREAD

**Issue by shyamperi** [openc/turbot-client#14]
**Error:**       Socket is not connected (Errno::ENOTCONN)
**Backtrace:**   

``` ruby
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/protocol.rb:211:in 'write'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/protocol.rb:211:in 'write0'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/protocol.rb:185:in 'block in write'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/protocol.rb:202:in 'writing'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/protocol.rb:184:in 'write'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http/generic_request.rb:325:in 'write_header'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http/generic_request.rb:182:in 'send_request_with_body'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http/generic_request.rb:130:in 'exec'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http.rb:1406:in 'block in transport_request'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in 'catch'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http.rb:1405:in 'transport_request'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http.rb:1378:in 'request'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient/net_http_ext.rb:51:in 'request'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:210:in 'block in transmit'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/2.1.0/net/http.rb:853:in 'start'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:206:in 'transmit'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:68:in 'execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient/request.rb:35:in 'execute'
/usr/local/lib/ruby/gems/2.1.0/gems/rest-client-1.6.8/lib/restclient.rb:74:in 'post'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:110:in 'request'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-api-0.0.14/lib/turbot_api/api.rb:54:in 'create_draft_data'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/lib/turbot/command/bots.rb:429:in 'submit_batch'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/lib/turbot/command/bots.rb:425:in 'handle_valid_record'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/processor.rb:24:in 'process'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/script_runner.rb:55:in 'run'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:72:in 'run_script'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:23:in 'block in run'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:22:in 'each'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-runner-0.1.14/lib/turbot_runner/runner.rb:22:in 'run'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/lib/turbot/command/bots.rb:293:in 'preview'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/lib/turbot/command.rb:219:in 'run'
/usr/local/Cellar/ruby/2.1.5/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/lib/turbot/cli.rb:28:in 'start'
/usr/local/lib/ruby/gems/2.1.0/gems/turbot-0.1.5/bin/turbot:17:in '<top (required)>'
/usr/local/bin/turbot:23:in 'load'
/usr/local/bin/turbot:23:in '<main>'
```

**Command:**     turbot bots:preview
**Version:**     turbot-gem/0.1.5 (x86_64-darwin14.0) ruby/2.1.5

**Comment by dariushoule** [comment]
I get this one intermittently as well. Would it be possible to do a few retries before killing the app? It's a bummer when this one happens after an hour or so running.

**Comment by sebbacon** [comment]
Yep, definitely a bummer. We'll look at this next week.
