### ISSUE TITLE
Failed to get bot info `turbot bots:info` 

### ISSUE THREAD

**Issue by signalpillar** [openc/turbot-client#21]
Problem
-----------

Failed to get `bots:info`

```

root@7451836bcd2e:/code# turbot bots:info
 !    Turbot client internal error.
 !    Report a bug at: https://github.com/openc/turbot-client/issues/new

    Error:       undefined method `get_bot' for #<Turbot::API:0x000000031338c0> (NoMethodError)
    Backtrace:   /opt/turbot-client/embedded/lib/ruby/gems/1.9.1/gems/turbot-0.1.6/lib/turbot/command/bots.rb:60:in `info'
                 /opt/turbot-client/embedded/lib/ruby/gems/1.9.1/gems/turbot-0.1.6/lib/turbot/command.rb:219:in `run'
                 /opt/turbot-client/embedded/lib/ruby/gems/1.9.1/gems/turbot-0.1.6/lib/turbot/cli.rb:28:in `start'
                 /opt/turbot-client/embedded/lib/ruby/gems/1.9.1/gems/turbot-0.1.6/bin/turbot:17:in `<top (required)>'
                 /opt/turbot-client/sbin/turbot:23:in `load'
                 /opt/turbot-client/sbin/turbot:23:in `<main>'

    Command:     turbot bots:info
    Version:     turbot-gem/0.1.6 (x86_64-linux) ruby/1.9.3
```

**Comment by jpmckinney** [comment]
Please update to the latest gem version.

**Comment by jpmckinney** [comment]
Noting that the issue is reproducible in 0.1.34.

**Comment by jpmckinney** [comment]
I can correct the error (see commit in branch below), but the API seems to have changed: information on the last run doesn't seem to be available anymore. The only data returned are bot_id, created_at, updated_at, and state.

https://github.com/openc/turbot-client/commit/4e072d5057d8dd6f27346c60225eae5f25f85a2b

**Comment by signalpillar** [comment]
@jpmckinney hi, unfortunately I'm not able to re-run tests again. Maybe it is really fixed in the newest version. Thanks.
